### ISSUE TITLE
Icons above the inventory bar

### ISSUE THREAD

**Issue by Terra1990** [V4M0N0S/project-crism#1]
Modpack: CRISM LITE

I have a display of item above the item bar.
I don't know where it's coming from but it's a bit annoying, maybe you can adjust it or tell me how to hide it.
![javaw_6QYp7EElcL](https://user-images.githubusercontent.com/50733930/149732162-b93e0173-b3d9-46e0-a0f0-bb52eb971391.png)

**Comment by V4M0N0S** [comment]
Its causing by an shitty mod we will remove in the next update. Thanks for report.
